######################################################################
##
## Filename: div25mhz.udo
## Created on: Wed Mar 13 8:53:32 PM Eastern Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
