######################################################################
##
## Filename: pongclk.udo
## Created on: Fri Mar 15 3:34:41 PM Eastern Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
