######################################################################
##
## Filename: test_ponggame.udo
## Created on: Sat Mar 16 2:02:06 AM Eastern Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
